-- horizonapi.area definition

-- Drop table

-- DROP TABLE horizonapi.area;

CREATE TABLE horizonapi.area (
	id serial4 NOT NULL,
	slug varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	description text NULL,
	"type" varchar(50) NULL,
	faction varchar(50) NULL,
	image_path varchar(100) NULL,
	CONSTRAINT area_pkey PRIMARY KEY (id),
	CONSTRAINT area_slug_key UNIQUE (slug)
);


-- horizonapi."characters" definition

-- Drop table

-- DROP TABLE horizonapi."characters";

CREATE TABLE horizonapi."characters" (
	id serial4 NOT NULL,
	slug varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	image_path varchar(255) NULL,
	culture varchar(255) NULL,
	gender varchar(50) NULL,
	profession varchar(255) NULL,
	status varchar(50) NULL,
	eyes_color varchar(50) NULL,
	hair_color varchar(50) NULL,
	birth_date varchar(255) NULL,
	death_date varchar(255) NULL,
	CONSTRAINT characters_pkey PRIMARY KEY (id),
	CONSTRAINT characters_slug_key UNIQUE (slug)
);


-- horizonapi.game definition

-- Drop table

-- DROP TABLE horizonapi.game;

CREATE TABLE horizonapi.game (
	id serial4 NOT NULL,
	slug varchar(50) NULL,
	"name" varchar(100) NULL,
	developer varchar(100) NULL,
	CONSTRAINT game_pkey PRIMARY KEY (id)
);


-- horizonapi.machines definition

-- Drop table

-- DROP TABLE horizonapi.machines;

CREATE TABLE horizonapi.machines (
	id serial4 NOT NULL,
	slug varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	path_image varchar(150) NULL,
	"size" varchar(50) NULL,
	weight varchar(50) NULL,
	origin varchar(50) NULL,
	"class" varchar(50) NULL,
	CONSTRAINT machines_pkey PRIMARY KEY (id),
	CONSTRAINT machines_slug_key UNIQUE (slug)
);


-- horizonapi.platform definition

-- Drop table

-- DROP TABLE horizonapi.platform;

CREATE TABLE horizonapi.platform (
	id serial4 NOT NULL,
	"name" varchar(50) NULL,
	CONSTRAINT platform_pkey PRIMARY KEY (id)
);


-- horizonapi.roles definition

-- Drop table

-- DROP TABLE horizonapi.roles;

CREATE TABLE horizonapi.roles (
	role_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_name int2 NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (role_id),
	CONSTRAINT roles_role_name_check CHECK (((role_name >= 0) AND (role_name <= 1)))
);


-- horizonapi.area_game definition

-- Drop table

-- DROP TABLE horizonapi.area_game;

CREATE TABLE horizonapi.area_game (
	id_area int4 NOT NULL,
	id_game int4 NOT NULL,
	CONSTRAINT area_game_pkey PRIMARY KEY (id_area, id_game),
	CONSTRAINT area_game_id_area_fkey FOREIGN KEY (id_area) REFERENCES horizonapi.area(id),
	CONSTRAINT area_game_id_game_fkey FOREIGN KEY (id_game) REFERENCES horizonapi.game(id)
);


-- horizonapi.character_game definition

-- Drop table

-- DROP TABLE horizonapi.character_game;

CREATE TABLE horizonapi.character_game (
	id_character int4 NOT NULL,
	id_game int4 NOT NULL,
	CONSTRAINT character_game_pkey PRIMARY KEY (id_character, id_game),
	CONSTRAINT character_game_id_character_fkey FOREIGN KEY (id_character) REFERENCES horizonapi."characters"(id),
	CONSTRAINT character_game_id_game_fkey FOREIGN KEY (id_game) REFERENCES horizonapi.game(id)
);


-- horizonapi.game_platform definition

-- Drop table

-- DROP TABLE horizonapi.game_platform;

CREATE TABLE horizonapi.game_platform (
	id_game int4 NOT NULL,
	id_platform int4 NOT NULL,
	release_date date NULL,
	CONSTRAINT game_platform_pkey PRIMARY KEY (id_game, id_platform),
	CONSTRAINT game_platform_id_game_fkey FOREIGN KEY (id_game) REFERENCES horizonapi.game(id),
	CONSTRAINT game_platform_id_platform_fkey FOREIGN KEY (id_platform) REFERENCES horizonapi.platform(id)
);


-- horizonapi.machine_explosive_components definition

-- Drop table

-- DROP TABLE horizonapi.machine_explosive_components;

CREATE TABLE horizonapi.machine_explosive_components (
	id_machine int4 NOT NULL,
	explosive_components varchar(50) NOT NULL,
	CONSTRAINT machine_explosive_components_pkey PRIMARY KEY (id_machine, explosive_components),
	CONSTRAINT machine_explosive_components_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.machine_game definition

-- Drop table

-- DROP TABLE horizonapi.machine_game;

CREATE TABLE horizonapi.machine_game (
	id_machine int4 NOT NULL,
	id_game int4 NOT NULL,
	CONSTRAINT machine_game_pkey PRIMARY KEY (id_machine, id_game),
	CONSTRAINT machine_game_id_game_fkey FOREIGN KEY (id_game) REFERENCES horizonapi.game(id),
	CONSTRAINT machine_game_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.machine_strength definition

-- Drop table

-- DROP TABLE horizonapi.machine_strength;

CREATE TABLE horizonapi.machine_strength (
	id_machine int4 NOT NULL,
	strength_name varchar(50) NOT NULL,
	CONSTRAINT machine_strength_pkey PRIMARY KEY (id_machine, strength_name),
	CONSTRAINT machine_strength_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.machine_weak_points definition

-- Drop table

-- DROP TABLE horizonapi.machine_weak_points;

CREATE TABLE horizonapi.machine_weak_points (
	id_machine int4 NOT NULL,
	weak_point_name varchar(100) NOT NULL,
	CONSTRAINT machine_weak_points_pkey PRIMARY KEY (id_machine, weak_point_name),
	CONSTRAINT machine_weak_points_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.machine_weakness definition

-- Drop table

-- DROP TABLE horizonapi.machine_weakness;

CREATE TABLE horizonapi.machine_weakness (
	id_machine int4 NOT NULL,
	weakness_name varchar(50) NOT NULL,
	CONSTRAINT machine_weakness_pkey PRIMARY KEY (id_machine, weakness_name),
	CONSTRAINT machine_weakness_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.region definition

-- Drop table

-- DROP TABLE horizonapi.region;

CREATE TABLE horizonapi.region (
	id serial4 NOT NULL,
	slug varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	description text NULL,
	id_area int4 NULL,
	image_path varchar(50) NULL,
	CONSTRAINT region_pkey PRIMARY KEY (id),
	CONSTRAINT region_slug_key UNIQUE (slug),
	CONSTRAINT region_id_area_fkey FOREIGN KEY (id_area) REFERENCES horizonapi.area(id)
);


-- horizonapi.region_faction definition

-- Drop table

-- DROP TABLE horizonapi.region_faction;

CREATE TABLE horizonapi.region_faction (
	id_region int4 NOT NULL,
	name_faction varchar(50) NOT NULL,
	CONSTRAINT region_faction_pkey PRIMARY KEY (id_region, name_faction),
	CONSTRAINT region_faction_id_region_fkey FOREIGN KEY (id_region) REFERENCES horizonapi.region(id)
);


-- horizonapi.users definition

-- Drop table

-- DROP TABLE horizonapi.users;

CREATE TABLE horizonapi.users (
	id varchar(255) NOT NULL,
	email varchar(150) NOT NULL,
	"password" varchar(255) NOT NULL,
	username varchar(100) NOT NULL,
	role_id int4 NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT ukkrvotbtiqhudlkamvlpaqus0t UNIQUE (role_id),
	CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES horizonapi.roles(role_id)
);


-- horizonapi.cauldron definition

-- Drop table

-- DROP TABLE horizonapi.cauldron;

CREATE TABLE horizonapi.cauldron (
	id serial4 NOT NULL,
	slug varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	description text NULL,
	path_image varchar(50) NULL,
	map_location varchar(50) NULL,
	id_region int4 NULL,
	CONSTRAINT cauldron_pkey PRIMARY KEY (id),
	CONSTRAINT cauldron_slug_key UNIQUE (slug),
	CONSTRAINT cauldron_id_region_fkey FOREIGN KEY (id_region) REFERENCES horizonapi.region(id)
);


-- horizonapi.enemie_cauldron definition

-- Drop table

-- DROP TABLE horizonapi.enemie_cauldron;

CREATE TABLE horizonapi.enemie_cauldron (
	id_machine int4 NOT NULL,
	id_cauldron int4 NOT NULL,
	CONSTRAINT enemie_cauldron_pkey PRIMARY KEY (id_machine, id_cauldron),
	CONSTRAINT enemie_cauldron_id_cauldron_fkey FOREIGN KEY (id_cauldron) REFERENCES horizonapi.cauldron(id),
	CONSTRAINT enemie_cauldron_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.machine_cauldron definition

-- Drop table

-- DROP TABLE horizonapi.machine_cauldron;

CREATE TABLE horizonapi.machine_cauldron (
	id_cauldron int4 NOT NULL,
	id_machine int4 NOT NULL,
	CONSTRAINT machine_cauldron_pkey PRIMARY KEY (id_cauldron, id_machine),
	CONSTRAINT machine_cauldron_id_cauldron_fkey FOREIGN KEY (id_cauldron) REFERENCES horizonapi.cauldron(id),
	CONSTRAINT machine_cauldron_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);


-- horizonapi.override_machine_cauldron definition

-- Drop table

-- DROP TABLE horizonapi.override_machine_cauldron;

CREATE TABLE horizonapi.override_machine_cauldron (
	id_machine int4 NOT NULL,
	id_cauldron int4 NOT NULL,
	CONSTRAINT override_machine_cauldron_pkey PRIMARY KEY (id_machine, id_cauldron),
	CONSTRAINT override_machine_cauldron_id_cauldron_fkey FOREIGN KEY (id_cauldron) REFERENCES horizonapi.cauldron(id),
	CONSTRAINT override_machine_cauldron_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id)
);

-- horizonapi.machine_game foreign keys

ALTER TABLE horizonapi.machine_game ADD CONSTRAINT machine_game_id_game_fkey FOREIGN KEY (id_game) REFERENCES horizonapi.game(id);
ALTER TABLE horizonapi.machine_game ADD CONSTRAINT machine_game_id_machine_fkey FOREIGN KEY (id_machine) REFERENCES horizonapi.machines(id);